# Generated by Django 5.2.5 on 2025-09-15 16:07

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blogcategory_blogpost_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="created_on",
            field=django_jalali.db.models.jDateTimeField(),
        ),
    ]
