# Generated by Django 5.2.5 on 2025-09-15 16:08

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blogpost_created_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="created_on",
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
