# Generated by Django 5.2.5 on 2025-09-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_blogpost_created_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(null=True, upload_to="blog_images/"),
        ),
    ]
