# Generated by Django 5.2.5 on 2025-09-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_blogpost_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(
                default="blog_images/default.png", upload_to="blog_images/"
            ),
        ),
    ]
