# Generated by Django 5.2.5 on 2025-09-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_blogpost_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="view_count",
            field=models.IntegerField(default=0),
        ),
    ]
