# Generated by Django 5.2.5 on 2025-10-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_alter_blogcomment_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogcomment",
            name="name",
            field=models.CharField(max_length=250),
        ),
    ]
